# Generated by Django 4.2.8 on 2023-12-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "User already exists with that number"},
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
    ]
