# Generated by Django 4.2.8 on 2023-12-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "_image",
                    models.ImageField(
                        blank=True, editable=False, null=True, upload_to="uzchess_clone/static/news_images/"
                    ),
                ),
                ("content", models.TextField()),
                ("views", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
            },
        ),
        migrations.CreateModel(
            name="Socials",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="static/socials/")),
            ],
            options={
                "verbose_name": "Social",
                "verbose_name_plural": "Socials",
            },
        ),
    ]
