# Generated by Django 4.2.8 on 2023-12-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socials",
            name="image",
            field=models.ImageField(blank=True, upload_to="static/socials/"),
        ),
    ]
