# Generated by Django 4.2.6 on 2023-11-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_social_news_socials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='socials',
        ),
    ]
