# Generated by Django 4.2.8 on 2023-12-16 05:54

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_socials_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socials",
            name="image",
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to="static/socials/"),
        ),
    ]
