# Generated by Django 4.2.7 on 2023-12-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_alter_book_description'),
        ('courses', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='book',
            field=models.ManyToManyField(blank=True, related_name='favourite', to='library.book'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='favourite', to='courses.course'),
        ),
    ]
