# Generated by Django 4.2.8 on 2023-12-14 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Chapter",
                "verbose_name_plural": "Chapters",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(blank=True, upload_to="uzchess_clone/static/courses_images/")),
                (
                    "lavel",
                    models.CharField(
                        choices=[("Beginner", "Beginner"), ("Amateur", "Amateur"), ("Professional", "Professional")],
                        max_length=32,
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0)),
                ("discount", models.PositiveIntegerField()),
                ("is_saved", models.BooleanField(default=False)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.CreateModel(
            name="UserLessonRewiew",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_lesson", to="courses.course"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "UserRewiew",
                "verbose_name_plural": "UserRewiews",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("video_path", models.FileField(upload_to="static/course-class_videos/")),
                ("chapter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.chapter")),
            ],
            options={
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
            },
        ),
        migrations.CreateModel(
            name="CourseComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.DecimalField(decimal_places=1, max_digits=2)),
                ("title", models.TextField()),
                ("cource", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.course")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "CourceComment",
                "verbose_name_plural": "CourceComments",
            },
        ),
        migrations.AddField(
            model_name="chapter",
            name="course",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.course"),
        ),
    ]
