# Generated by Django 4.2.8 on 2023-12-17 06:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Chapter",
            new_name="CourseChapter",
        ),
        migrations.RenameModel(
            old_name="Lesson",
            new_name="CourseLesson",
        ),
    ]
