# Generated by Django 4.2.8 on 2023-12-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_category_alter_course_lavel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="lavel",
            field=models.CharField(choices=[("Beginner", "Beginner"), ("Amateur", "Beginner")], max_length=32),
        ),
    ]
